Ensure secrets are set in workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,10 +15,44 @@ on:
         default: 'Stage'
 
 jobs:
+  secrets-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check DEPLOY_SERVER
+        run: |
+          if [ -z "${{ secrets.DEPLOY_SERVER }}" ]; then
+            echo "Error: DEPLOY_SERVER not set."
+            exit 1
+          fi
+
+      - name: Check DEPLOY_USER
+        run: |
+          if [ -z "${{ secrets.DEPLOY_USER }}" ]; then
+            echo "Error: DEPLOY_USER not set."
+            exit 1
+          fi
+
+      - name: Check DEPLOY_PATH
+        run: |
+          if [ -z "${{ secrets.DEPLOY_PATH }}" ]; then
+            echo "Error: DEPLOY_PATH not set."
+            exit 1
+          fi
+
+      - name: Check SSH_PRIVATE_KEY
+        run: |
+          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
+            echo "Error: SSH_PRIVATE_KEY not set."
+            exit 1
+          fi
+
   deploy:
     runs-on: ubuntu-latest
+    needs: secrets-check
     environment: ${{ inputs.environment || 'Production' }}
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
+    if: >-
+      ${{ (github.event.workflow_run.conclusion == 'success') ||
+          (github.event_name == 'workflow_dispatch') }}
 
     env:
       DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
diff --git a/.github/workflows/update_models.yml b/.github/workflows/update_models.yml
--- a/.github/workflows/update_models.yml
+++ b/.github/workflows/update_models.yml
@@ -15,8 +15,40 @@ on:
         default: 'Stage'
 
 jobs:
+  secrets-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check DEPLOY_SERVER
+        run: |
+          if [ -z "${{ secrets.DEPLOY_SERVER }}" ]; then
+            echo "Error: DEPLOY_SERVER not set."
+            exit 1
+          fi
+
+      - name: Check DEPLOY_USER
+        run: |
+          if [ -z "${{ secrets.DEPLOY_USER }}" ]; then
+            echo "Error: DEPLOY_USER not set."
+            exit 1
+          fi
+
+      - name: Check DEPLOY_PATH
+        run: |
+          if [ -z "${{ secrets.DEPLOY_PATH }}" ]; then
+            echo "Error: DEPLOY_PATH not set."
+            exit 1
+          fi
+
+      - name: Check SSH_PRIVATE_KEY
+        run: |
+          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
+            echo "Error: SSH_PRIVATE_KEY not set."
+            exit 1
+          fi
+
   update-models:
     runs-on: ubuntu-latest
+    needs: secrets-check
     environment: ${{ inputs.environment || 'Production' }}
 
     env:
@@ -39,19 +71,38 @@ jobs:
         run: ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
 
       - name: List models on PR merge
-        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
+        if: >-
+          github.event_name == 'pull_request' &&
+          github.event.pull_request.merged == true
         run: |
           git fetch origin main
-          git diff --name-only --diff-filter=AM origin/main...${{ github.sha }} | grep '^models/.*\.yml$' > models.txt || true
+          git diff \
+            --name-only \
+            --diff-filter=AM origin/main...${{ github.sha }} | \
+            grep '^models/.*\.yml$' > models.txt || true
+
+      - name: List models on workflow_dispatch
+        if: github.event_name == 'workflow_dispatch'
+        run: |
+          git fetch origin main
+          ls -1 models/*.yml > models.txt
 
       - name: Set model sync trigger
         id: model_check
-        run: echo "model_sync_trigger=$(if [ -s models.txt ]; then echo true; else echo false; fi)" >> $GITHUB_ENV
+        run: |
+          echo "model_sync_trigger=$(
+            if [ -s models.txt ]; then
+              echo true;
+            else
+              echo false;
+            fi
+          )" >> $GITHUB_ENV
 
       - name: Sync models
         if: ${{ env.model_sync_trigger == 'true' }}
         run: |
-            rsync -avz --files-from=models.txt ./ $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH/
+            rsync -avz --files-from=models.txt \
+              ./ $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH/
             ssh $DEPLOY_USER@$DEPLOY_SERVER << EOF
               cd $DEPLOY_PATH
               ./vendor/bin/drush scr scripts/sync_models.php
